static long op_rb0a()		;					
static long op_rb0b()		;					
static long op_rb0c()		;					
static long op_rb0d()		;					
static long op_rb0e()		;					
static long op_rb0h()		;					
static long op_rb0hl()		;					
static long op_rb0l()		;					
static long op_rb1a()		;					
static long op_rb1b()		;					
static long op_rb1c()		;					
static long op_rb1d()		;					
static long op_rb1e()		;					
static long op_rb1h()		;					
static long op_rb1hl()		;					
static long op_rb1l()		;					
static long op_rb2a()		;					
static long op_rb2b()		;					
static long op_rb2c()		;					
static long op_rb2d()		;					
static long op_rb2e()		;					
static long op_rb2h()		;					
static long op_rb2hl()		;					
static long op_rb2l()		;					
static long op_rb3a()		;					
static long op_rb3b()		;					
static long op_rb3c()		;					
static long op_rb3d()		;					
static long op_rb3e()		;					
static long op_rb3h()		;					
static long op_rb3hl()		;					
static long op_rb3l()		;					
static long op_rb4a()		;					
static long op_rb4b()		;					
static long op_rb4c()		;					
static long op_rb4d()		;					
static long op_rb4e()		;					
static long op_rb4h()		;					
static long op_rb4hl()		;					
static long op_rb4l()		;					
static long op_rb5a()		;					
static long op_rb5b()		;					
static long op_rb5c()		;					
static long op_rb5d()		;					
static long op_rb5e()		;					
static long op_rb5h()		;					
static long op_rb5hl()		;					
static long op_rb5l()		;					
static long op_rb6a()		;					
static long op_rb6b()		;					
static long op_rb6c()		;					
static long op_rb6d()		;					
static long op_rb6e()		;					
static long op_rb6h()		;					
static long op_rb6hl()		;					
static long op_rb6l()		;					
static long op_rb7a()		;					
static long op_rb7b()		;					
static long op_rb7c()		;					
static long op_rb7d()		;					
static long op_rb7e()		;					
static long op_rb7h()		;					
static long op_rb7hl()		;					
static long op_rb7l()		;					
static long op_rlb()		;					
static long op_rlc()		;					
static long op_rlcb()		;					
static long op_rlcc()		;					
static long op_rlcd()		;					
static long op_rlce()		;					
static long op_rlch()		;					
static long op_rlchl()		;					
static long op_rlcl()		;					
static long op_rlcra()		;					
static long op_rld()		;					
static long op_rle()		;					
static long op_rlh()		;					
static long op_rlhl()		;					
static long op_rll()		;					
static long op_rlra()		;					
static long op_rrb()		;					
static long op_rrc()		;					
static long op_rrcb()		;					
static long op_rrcc()		;					
static long op_rrcd()		;					
static long op_rrce()		;					
static long op_rrch()		;					
static long op_rrchl()		;					
static long op_rrcl()		;					
static long op_rrcra()		;					
static long op_rrd()		;					
static long op_rre()		;					
static long op_rrh()		;					
static long op_rrhl()		;					
static long op_rrl()		;					
static long op_rrra()		;					
static long op_sb0a()		;					
static long op_sb0b()		;					
static long op_sb0c()		;					
static long op_sb0d()		;					
static long op_sb0e()		;					
static long op_sb0h()		;					
static long op_sb0hl()		;					
static long op_sb0l()		;					
static long op_sb1a()		;					
static long op_sb1b()		;					
static long op_sb1c()		;					
static long op_sb1d()		;					
static long op_sb1e()		;					
static long op_sb1h()		;					
static long op_sb1hl()		;					
static long op_sb1l()		;					
static long op_sb2a()		;					
static long op_sb2b()		;					
static long op_sb2c()		;					
static long op_sb2d()		;					
static long op_sb2e()		;					
static long op_sb2h()		;					
static long op_sb2hl()		;					
static long op_sb2l()		;					
static long op_sb3a()		;					
static long op_sb3b()		;					
static long op_sb3c()		;					
static long op_sb3d()		;					
static long op_sb3e()		;					
static long op_sb3h()		;					
static long op_sb3hl()		;					
static long op_sb3l()		;					
static long op_sb4a()		;					
static long op_sb4b()		;					
static long op_sb4c()		;					
static long op_sb4d()		;					
static long op_sb4e()		;					
static long op_sb4h()		;					
static long op_sb4hl()		;					
static long op_sb4l()		;					
static long op_sb5a()		;					
static long op_sb5b()		;					
static long op_sb5c()		;					
static long op_sb5d()		;					
static long op_sb5e()		;					
static long op_sb5h()		;					
static long op_sb5hl()		;					
static long op_sb5l()		;					
static long op_sb6a()		;					
static long op_sb6b()		;					
static long op_sb6c()		;					
static long op_sb6d()		;					
static long op_sb6e()		;					
static long op_sb6h()		;					
static long op_sb6hl()		;					
static long op_sb6l()		;					
static long op_sb7a()		;					
static long op_sb7b()		;					
static long op_sb7c()		;					
static long op_sb7d()		;					
static long op_sb7e()		;					
static long op_sb7h()		;					
static long op_sb7hl()		;					
static long op_sb7l()		;					
static long op_slaa()		;					
static long op_slab()		;					
static long op_slac()		;					
static long op_slad()		;					
static long op_slae()		;					
static long op_slah()		;					
static long op_slahl()		;					
static long op_slal()		;					
static long op_sraa()		;					
static long op_srab()		;					
static long op_srac()		;					
static long op_srad()		;					
static long op_srae()		;					
static long op_srah()		;					
static long op_srahl()		;					
static long op_sral()		;					
static long op_srla()		;					
static long op_srlb()		;					
static long op_srlc()		;					
static long op_srld()		;					
static long op_srle()		;					
static long op_srlh()		;					
static long op_srlhl()		;					
static long op_srll()		;					
static long op_tb0a()		;					
static long op_tb0b()		;					
static long op_tb0c()		;					
static long op_tb0d()		;					
static long op_tb0e()		;					
static long op_tb0h()		;					
static long op_tb0hl()		;					
static long op_tb0l()		;					
static long op_tb1a()		;					
static long op_tb1b()		;					
static long op_tb1c()		;					
static long op_tb1d()		;					
static long op_tb1e()		;					
static long op_tb1h()		;					
static long op_tb1hl()		;					
static long op_tb1l()		;					
static long op_tb2a()		;					
static long op_tb2b()		;					
static long op_tb2c()		;					
static long op_tb2d()		;					
static long op_tb2e()		;					
static long op_tb2h()		;					
static long op_tb2hl()		;					
static long op_tb2l()		;					
static long op_tb3a()		;					
static long op_tb3b()		;					
static long op_tb3c()		;					
static long op_tb3d()		;					
static long op_tb3e()		;					
static long op_tb3h()		;					
static long op_tb3hl()		;					
static long op_tb3l()		;					
static long op_tb4a()		;					
static long op_tb4b()		;					
static long op_tb4c()		;					
static long op_tb4d()		;					
static long op_tb4e()		;					
static long op_tb4h()		;					
static long op_tb4hl()		;					
static long op_tb4l()		;					
static long op_tb5a()		;					
static long op_tb5b()		;					
static long op_tb5c()		;					
static long op_tb5d()		;					
static long op_tb5e()		;					
static long op_tb5h()		;					
static long op_tb5hl()		;					
static long op_tb5l()		;					
static long op_tb6a()		;					
static long op_tb6b()		;					
static long op_tb6c()		;					
static long op_tb6d()		;					
static long op_tb6e()		;					
static long op_tb6h()		;					
static long op_tb6hl()		;					
static long op_tb6l()		;					
static long op_tb7a()		;					
static long op_tb7b()		;					
static long op_tb7c()		;					
static long op_tb7d()		;					
static long op_tb7e()		;					
static long op_tb7h()		;					
static long op_tb7hl()		;					
static long op_tb7l()		;					
static long trap_cb()		;	





static long op_adca()		;
static long op_adcb()		;
static long op_adcc()		;
static long op_adcd()		;
static long op_adce()		;
static long op_adch()		;
static long op_adchl()		;
static long op_adcl()		;
static long op_adcn()		;
static long op_adda()		;
static long op_addb()		;
static long op_addc()		;
static long op_addd()		;
static long op_adde()		;
static long op_addh()		;
static long op_addhl()		;
static long op_addl()		;
static long op_addn()		;
static long op_adhlbc()		;
static long op_adhlde()		;
static long op_adhlhl()		;
static long op_adhlsp()		;
static long op_anda()		;
static long op_andb()		;
static long op_andc()		;
static long op_andd()		;
static long op_ande()		;
static long op_andh()		;
static long op_andhl()		;
static long op_andl()		;
static long op_andn()		;
static long op_calc()		;
static long op_call()		;
static long op_calm()		;
static long op_calnc()		;
static long op_calnz()		;
static long op_calp()		;
static long op_calpe()		;
static long op_calpo()		;
static long op_calz()		;
static long op_ccf()		;
static long op_cpa()		;
static long op_cpb()		;
static long op_cpc()		;
static long op_cpd()		;
static long op_cpe()		;
static long op_cph()		;
static long op_cphl()		;
static long op_cpl()		;
static long op_cplr()		;
static long op_cpn()		;
static long op_daa()		;
static long op_deca()		;
static long op_decb()		;
static long op_decbc()		;
static long op_decc()		;
static long op_decd()		;
static long op_decde()		;
static long op_dece()		;
static long op_dech()		;
static long op_dechl()		;
static long op_decihl()		;
static long op_decl()		;
static long op_decsp()		;
static long op_di()		;
static long op_djnz()		;
static long op_ei()		;
static long op_exafaf()		;
static long op_exdehl()		;
static long op_exsphl()		;
static long op_exx()		;
static long op_halt()		;
static long op_in()		;
static long op_inca()		;
static long op_incb()		;
static long op_incbc()		;
static long op_incc()		;
static long op_incd()		;
static long op_incde()		;
static long op_ince()		;
static long op_inch()		;
static long op_inchl()		;
static long op_incihl()		;
static long op_incl()		;
static long op_incsp()		;
static long op_jp()		;
static long op_jpc()		;
static long op_jphl()		;
static long op_jpm()		;
static long op_jpnc()		;
static long op_jpnz()		;
static long op_jpp()		;
static long op_jppe()		;
static long op_jppo()		;
static long op_jpz()		;
static long op_jr()		;
static long op_jrc()		;
static long op_jrnc()		;
static long op_jrnz()		;
static long op_jrz()		;
static long op_ldaa()		;
static long op_ldab()		;
static long op_ldabc()		;
static long op_ldac()		;
static long op_ldad()		;
static long op_ldade()		;
static long op_ldae()		;
static long op_ldah()		;
static long op_ldahl()		;
static long op_ldal()		;
static long op_ldan()		;
static long op_ldann()		;
static long op_ldba()		;
static long op_ldbb()		;
static long op_ldbc()		;
static long op_ldbca()		;
static long op_ldbcnn()		;
static long op_ldbd()		;
static long op_ldbe()		;
static long op_ldbh()		;
static long op_ldbhl()		;
static long op_ldbl()		;
static long op_ldbn()		;
static long op_ldca()		;
static long op_ldcb()		;
static long op_ldcc()		;
static long op_ldcd()		;
static long op_ldce()		;
static long op_ldch()		;
static long op_ldchl()		;
static long op_ldcl()		;
static long op_ldcn()		;
static long op_ldda()		;
static long op_lddb()		;
static long op_lddc()		;
static long op_lddd()		;
static long op_ldde()		;
static long op_lddea()		;
static long op_lddenn()		;
static long op_lddh()		;
static long op_lddhl()		;
static long op_lddl()		;
static long op_lddn()		;
static long op_ldea()		;
static long op_ldeb()		;
static long op_ldec()		;
static long op_lded()		;
static long op_ldee()		;
static long op_ldeh()		;
static long op_ldehl()		;
static long op_ldel()		;
static long op_lden()		;
static long op_ldha()		;
static long op_ldhb()		;
static long op_ldhc()		;
static long op_ldhd()		;
static long op_ldhe()		;
static long op_ldhh()		;
static long op_ldhhl()		;
static long op_ldhl()		;
static long op_ldhl1()		;
static long op_ldhla()		;
static long op_ldhlb()		;
static long op_ldhlc()		;
static long op_ldhld()		;
static long op_ldhle()		;
static long op_ldhlh()		;
static long op_ldhlin()		;
static long op_ldhll()		;
static long op_ldhlnn()		;
static long op_ldhn()		;
static long op_ldinhl()		;
static long op_ldla()		;
static long op_ldlb()		;
static long op_ldlc()		;
static long op_ldld()		;
static long op_ldle()		;
static long op_ldlh()		;
static long op_ldlhl()		;
static long op_ldll()		;
static long op_ldln()		;
static long op_ldnna()		;
static long op_ldsphl()		;
static long op_ldspnn()		;
static long op_nop()		;
static long op_notimpl()		;
static long op_ora()		;
static long op_orb()		;
static long op_orc()		;
static long op_ord()		;
static long op_ore()		;
static long op_orh()		;
static long op_orhl()		;
static long op_orl()		;
static long op_orn()		;
static long op_out()		;
static long op_popaf()		;
static long op_popbc()		;
static long op_popde()		;
static long op_pophl()		;
static long op_pushaf()		;
static long op_pushbc()		;
static long op_pushde()		;
static long op_pushhl()		;
static long op_ret()		;
static long op_retc()		;
static long op_retm()		;
static long op_retnc()		;
static long op_retnz()		;
static long op_retp()		;
static long op_retpe()		;
static long op_retpo()		;
static long op_retz()		;
static long op_rla()		;
static long op_rlca()		;
static long op_rra()		;
static long op_rrca()		;
static long op_rst00()		;
static long op_rst08()		;
static long op_rst10()		;
static long op_rst18()		;
static long op_rst20()		;
static long op_rst28()		;
static long op_rst30()		;
static long op_rst38()		;
static long op_sbca()		;
static long op_sbcb()		;
static long op_sbcc()		;
static long op_sbcd()		;
static long op_sbce()		;
static long op_sbch()		;
static long op_sbchl()		;
static long op_sbcl()		;
static long op_sbcn()		;
static long op_scf()		;
static long op_suba()		;
static long op_subb()		;
static long op_subc()		;
static long op_subd()		;
static long op_sube()		;
static long op_subh()		;
static long op_subhl()		;
static long op_subl()		;
static long op_subn()		;
static long op_xora()		;
static long op_xorb()		;
static long op_xorc()		;
static long op_xord()		;
static long op_xore()		;
static long op_xorh()		;
static long op_xorhl()		;
static long op_xorl()		;
static long op_xorn()		;

static long op_acaxd()		;
static long op_adaxd()		;
static long op_addxb()		;
static long op_addxd()		;
static long op_addxs()		;
static long op_addxx()		;
static long op_andxd()		;
static long op_cpxd()		;
static long op_decix()		;
static long op_decxd()		;
static long op_exspx()		;
static long op_incix()		;
static long op_incxd()		;
static long op_jpix()		;
static long op_ldaxd()		;
static long op_ldbxd()		;
static long op_ldcxd()		;
static long op_lddxd()		;
static long op_ldexd()		;
static long op_ldhxd()		;
static long op_ldinx()		;
static long op_ldixinn()	;
static long op_ldixnn()		;
static long op_ldlxd()		;
static long op_ldspx()		;
static long op_ldxda()		;
static long op_ldxdb()		;
static long op_ldxdc()		;
static long op_ldxdd()		;
static long op_ldxde()		;
static long op_ldxdh()		;
static long op_ldxdl()		;
static long op_ldxdn()		;
static long op_orxd()		;
static long op_popix()		;
static long op_pusix()		;
static long op_scaxd()		;
static long op_suaxd()		;
static long op_xorxd()		;
static long trap_dd()		;
				


static long op_adchb()		;
static long op_adchd()		;
static long op_adchh()		;
static long op_adchs()		;
static long op_cpdop()		;
static long op_cpdr()		;
static long op_cpi()		;
static long op_cpir()		;
static long op_im0()		;
static long op_im1()		;
static long op_im2()		;
static long op_inaic()		;
static long op_inbic()		;
static long op_incic()		;
static long op_ind()		;
static long op_indic()		;
static long op_indr()		;
static long op_ineic()		;
static long op_inhic()		;
static long op_ini()		;
static long op_inir()		;
static long op_inlic()		;
static long op_ldai()		;
static long op_ldar()		;
static long op_ldbcinn()	     	;
static long op_ldd()		;
static long op_lddeinn()	     ;
static long op_lddr()		;
static long op_ldi()		;
static long op_ldia()		;
static long op_ldinbc()		;
static long op_ldinde()		;
static long op_ldinsp()		;
static long op_ldir()		;
static long op_ldra()		;
static long op_ldspinn()	     ;
static long op_neg()		;
static long op_oprld()		;
static long op_oprrd()		;
static long op_otdr()		;
static long op_otir()		;
static long op_outca()		;
static long op_outcb()		;
static long op_outcc()		;
static long op_outcd()		;
static long op_outce()		;
static long op_outch()		;
static long op_outcl()		;
static long op_outd()		;
static long op_outi()		;
static long op_reti()		;
static long op_retn()		;
static long op_sbchb()		;
static long op_sbchd()		;
static long op_sbchh()		;
static long op_sbchs()		;
static long trap_ed()		;


static long op_acayd()		;
static long op_adayd()		;
static long op_addyb()		;
static long op_addyd()		;
static long op_addys()		;
static long op_addyy()		;
static long op_andyd()		;
static long op_cpyd()		;
static long op_deciy()		;
static long op_decyd()		;
static long op_exspy()		;
static long op_inciy()		;
static long op_incyd()		;
static long op_jpiy()		;
static long op_ldayd()		;
static long op_ldbyd()		;
static long op_ldcyd()		;
static long op_lddyd()		;
static long op_ldeyd()		;
static long op_ldhyd()		;
static long op_ldiny()		;
static long op_ldiyinn()     ;
static long op_ldiynn()		;
static long op_ldlyd()		;
static long op_ldspy()		;
static long op_ldyda()		;
static long op_ldydb()		;
static long op_ldydc()		;
static long op_ldydd()		;
static long op_ldyde()		;
static long op_ldydh()		;
static long op_ldydl()		;
static long op_ldydn()		;
static long op_oryd()		;
static long op_popiy()		;
static long op_pusiy()		;
static long op_scayd()		;
static long op_suayd()		;
static long op_xoryd()		;


static long op_rb0ixd(int data)	;
static long op_rb1ixd(int data)	;
static long op_rb2ixd(int data)	;
static long op_rb3ixd(int data)	;
static long op_rb4ixd(int data)	;
static long op_rb5ixd(int data)	;
static long op_rb6ixd(int data)	;
static long op_rb7ixd(int data)	;
static long op_rlcixd(int data)	;
static long op_rlixd(int data)	;
static long op_rrcixd(int data)	;
static long op_rrixd(int data)	;
static long op_sb0ixd(int data)	;
static long op_sb1ixd(int data)	;
static long op_sb2ixd(int data)	;
static long op_sb3ixd(int data)	;
static long op_sb4ixd(int data)	;
static long op_sb5ixd(int data)	;
static long op_sb6ixd(int data)	;
static long op_sb7ixd(int data)	;
static long op_slaixd(int data)	;
static long op_sraixd(int data)	;
static long op_srlixd(int data)	;
static long op_tb0ixd(int data)	;
static long op_tb1ixd(int data)	;
static long op_tb2ixd(int data)	;
static long op_tb3ixd(int data)	;
static long op_tb4ixd(int data)	;
static long op_tb5ixd(int data)	;
static long op_tb6ixd(int data)	;
static long op_tb7ixd(int data)	;

static long op_rb0iyd(int data)	;
static long op_rb1iyd(int data)	;
static long op_rb2iyd(int data)	;
static long op_rb3iyd(int data)	;
static long op_rb4iyd(int data)	;
static long op_rb5iyd(int data)	;
static long op_rb6iyd(int data)	;
static long op_rb7iyd(int data)	;
static long op_rlciyd(int data)	;
static long op_rliyd(int data)	;
static long op_rrciyd(int data)	;
static long op_rriyd(int data)	;
static long op_sb0iyd(int data)	;
static long op_sb1iyd(int data)	;
static long op_sb2iyd(int data)	;
static long op_sb3iyd(int data)	;
static long op_sb4iyd(int data)	;
static long op_sb5iyd(int data)	;
static long op_sb6iyd(int data)	;
static long op_sb7iyd(int data)	;
static long op_slaiyd(int data)	;
static long op_sraiyd(int data)	;
static long op_srliyd(int data)	;
static long op_tb0iyd(int data)	;
static long op_tb1iyd(int data)	;
static long op_tb2iyd(int data)	;
static long op_tb3iyd(int data)	;
static long op_tb4iyd(int data)	;
static long op_tb5iyd(int data)	;
static long op_tb6iyd(int data)	;
static long op_tb7iyd(int data)	;

static long trap_fdcb();
static long trap_ddcb();
static long trap_fd();
static void quit_int();
static void user_int();
static do_step();

void reload_cpm_warm (void);
